### ISSUE TITLE
Discussão da lista: Lançamentos

### ISSUE THREAD

**Issue by edmolima** [Ifactory-Solutions/planilhareembolso#18]
@juliosampaio e @wellingtonamaralleitao eu pensei algo proximo a essa ideia aqui de lista: [tabela](http://codepen.io/anon/pen/NGEgKe)

O Cara vai adicionar

* Data (podemos usar algum datepicker, e o moment caso necessario para trabalhar com essas datas ai).

* Tipo de despesa: Pensei em adicionar um Select com os tipos de despesas consideradas padrões. Porem poderia ter uma opção ja dentro desse select do cara criar um novo tipo de despesa e salvaria no "plano de despesa". Isso ai podemos discutir depois caso não tenha intendido.

* Valor: basicamente um input que vai ser aceito apenas valor ja tratando o valor adicionando virgula e etc.

*Justificativa: Também não tem segredo, apenas adicionar um texto de justificativa.

* Status: As vezes pode acontecer de o kra adicionar uma despesa, mas não ter tirado a foto do comprovante, então é algo pra o kra ter a certeza de que tirou a foto e ja colocou no pacote do zip. Afinal ele pode lançar tudo, e depois apenas fotografar e ir conferindo. Ele pode ser um campo de true ou false, e pode ter apenas um checkbox ou icone.

* Ações: Basicamente uma opção que habilita a edição ou exclusão daquele lançamento. Nada demais aqui,

Se concordarem com essa estrutura irei fazer o front de como imaginei a tela real.

Isso eu falo somente a lista, alem disso tem o topo da planilha que envolve: Projeto, conta corrente, adiantamento e etc. Isso ainda vou pensar como podera ficar.

E tambem falta o footer que criarei uma outra discussão de como poderemos fazer ele, basicamente ele vai ter o valor total, e acredito que o nome do kra que podera altorizar e uma flag que diz que ele altorizou ou não. Podemos discutir posterirmente.

**Comment by edmolima** [comment]
@juliosampaio imaginei baseado nessa [ideia](http://tableless.github.io/exemplos/angularjs/lista-compras/)

**Comment by wellingtonamaralleitao** [comment]
Se eu não me engano para o datepicker eu havia feito um teste com o do Jquery UI e não havia conseguido capturar o valor pelo ng-model. Fiz um teste com o <a href="https://github.com/720kb/angular-datepicker" target="_blank">esse aqui</a> e funcionou perfeitamente com angular.

A respeito do tipo de despesa a gente poderia colocar como você disse no dropdown as que já são padrão e uma opção "outro" caso o cara escolha essa opção aparece um "input text" por cara digitar o que quer. Deixar a galera cadastrar o que quiser e aparecer pra todo mundo, acho que abre margens e foge do controle.

Sobre as imagens dos recibos. Vamos fazer pra cada despesa eu tenho que cadastrar uma imagem? Minha sugestão é que tenha uma opção de no final de cada preenchimento de planilha tenha a opção pra gente adicionar um anexo com todos os recibos, porque senão ficaria mais trabalho para o funcionário ficar cadastrando o recibo do dia x na despesa x.

**Comment by edmolima** [comment]
Esse lance do input falo mais no sentido de salvar no plano de contas do cara, e não disponibilizar pra todos, vc tem razão sairia do controle. Chegariamos a ter: 'Almoço, Jantar, Alimentação' como tipo de despesa. mas realmente assim é ter a padrão e se ele adicionar um tipo de despesa nova fica so pra ele esse tipo de despesa..


Sobre o recibo, os anexos sera um pacote so, da mais trabalho mesmo se for de um por um. Mas essa flag que falei ai é mais a nivel de conferir. Por que eu posso lançar todo dia minhas coisas sem anexar nada. e no ultimo dia tirar as fotos dos comprovantes todos . e ir so conferindo e colocando sei la :+1:  para as coisas q tenho comprovante e :-1: para o que não fotografei ainda.

**Comment by wellingtonamaralleitao** [comment]
Entendi, concordo.
